import argparse
from pathlib import Path

from coderoll.config import load_config
from coderoll.runner import run_from_config


# Default quickstart config (TOML keeps this dependency-free).
DEFAULT_CONFIG_PATH = Path("quickStart/file_mode_experiment.toml")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run a coderoll quickstart config from Python SDK.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
        help="Path to a TOML/YAML config file.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Parse and validate config into a typed RunConfig object.
    config = load_config(args.config)
    # Execute the run and collect all candidate results.
    results = run_from_config(config)

    # Print a compact summary (total, passed, failed, timing, etc.).
    print("summary:", results.summary())
    # Fetch the highest-ranked result, if one exists.
    best = results.best()
    if best is not None:
        print(
            "best:",
            {
                # Candidate identifier from input data.
                "candidate_id": best.candidate_id,
                # Final aggregated score used for ranking.
                "score": best.score,
                # Whether this candidate passed all required checks.
                "passed": best.passed,
            },
        )
    # Location of the raw JSONL output generated by this run.
    print("output:", config.output_path)


if __name__ == "__main__":
    main()
